sonar.projectKey=vielkab_SonarQube-Arquitectura
sonar.organization=vielkab
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.{test,spec}.{js,jsx,ts,tsx}
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.test.{js,jsx,ts,tsx},**/*.spec.{js,jsx,ts,tsx}
